export const themes = {
  light: {
    background: 'bg-gradient-to-br from-blue-50 to-indigo-100',
    card: 'bg-white',
    text: 'text-gray-900',
    textSecondary: 'text-gray-600',
  },
  dark: {
    background: 'bg-gradient-to-br from-gray-900 to-black',
    card: 'bg-gray-800',
    text: 'text-white',
    textSecondary: 'text-gray-300',
  },
}

export const linkColors = [
  'from-blue-500 to-purple-500',
  'from-pink-500 to-orange-500',
  'from-green-500 to-teal-500',
  'from-yellow-500 to-red-500',
  'from-indigo-500 to-blue-500',
  'from-purple-500 to-pink-500',
  'from-gray-700 to-gray-900',
  'from-emerald-500 to-green-500',
  'from-rose-500 to-pink-500',
  'from-cyan-500 to-blue-500',
]

export const iconOptions = [
  'globe',
  'instagram',
  'github',
  'twitter',
  'linkedin',
  'youtube',
  'facebook',
  'tiktok',
  'twitch',
  'discord',
  'spotify',
  'apple',
  'google',
  'mail',
  'phone',
  'star',
  'heart',
  'user',
  'briefcase',
  'camera',
  'music',
  'video',
  'book',
  'coffee',
  'rocket',
  'gamepad',
  'shopping-bag',
  'map-pin',
  'calendar',
]